<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- When inside VS, only the latest target is built, both for performance and for live unit testing -->
    <TargetFrameworks Condition=" '$(BuildingInsideVisualStudio)' != 'true' ">net10.0;net9.0;net461;net47</TargetFrameworks>
    <TargetFrameworks Condition=" '$(BuildingInsideVisualStudio)' == 'true' ">net10.0</TargetFrameworks>
    <AssemblyName>Dangl.Calculator.Tests</AssemblyName>
    <PackageId>Dangl.Calculator.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net461' Or '$(TargetFramework)' == 'net47'">
    <USE_OLD_XUNIT>true</USE_OLD_XUNIT>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dangl.Calculator\Dangl.Calculator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="XunitXml.TestLogger" Version="[5.0.0]" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="$(USE_OLD_XUNIT) == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup Condition="$(USE_OLD_XUNIT) != 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
