<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- When inside VS, only the latest target is built, both for performance and for live unit testing -->
    <TargetFrameworks Condition=" '$(BuildingInsideVisualStudio)' != 'true' ">net10.0;net9.0;net472</TargetFrameworks>
    <TargetFrameworks Condition=" '$(BuildingInsideVisualStudio)' == 'true' ">net10.0</TargetFrameworks>
    <AssemblyName>Dangl.Calculator.Tests</AssemblyName>
    <PackageId>Dangl.Calculator.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dangl.Calculator\Dangl.Calculator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
